// <auto-generated />
using System;
using Autocomplete.Data.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Autocomplete.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    partial class MeuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Autocomplete.Business.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("country")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("geonameid")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("name")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("subcountry")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Citys");
                });
#pragma warning restore 612, 618
        }
    }
}
